-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.academic_sequences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academic_year character varying NOT NULL,
  term character varying NOT NULL CHECK (term::text = ANY (ARRAY['Term 1'::character varying, 'Term 2'::character varying, 'Term 3'::character varying, 'first'::character varying, 'second'::character varying, 'third'::character varying]::text[])),
  sequence_number integer NOT NULL,
  sequence_name character varying NOT NULL,
  start_date date,
  end_date date,
  max_marks integer DEFAULT 20,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academic_sequences_pkey PRIMARY KEY (id)
);
CREATE TABLE public.alert_group_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  group_id uuid NOT NULL,
  parent_id uuid NOT NULL,
  student_id character varying NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT alert_group_members_pkey PRIMARY KEY (id),
  CONSTRAINT alert_group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.alert_groups(id),
  CONSTRAINT alert_group_members_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id),
  CONSTRAINT alert_group_members_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id)
);
CREATE TABLE public.alert_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  group_type character varying NOT NULL CHECK (group_type::text = ANY (ARRAY['class'::character varying, 'grade'::character varying, 'custom'::character varying, 'all'::character varying]::text[])),
  criteria jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT alert_groups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.alert_recipients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  alert_id uuid NOT NULL,
  parent_id uuid NOT NULL,
  student_id character varying NOT NULL,
  delivery_method character varying NOT NULL CHECK (delivery_method::text = ANY (ARRAY['sms'::character varying, 'email'::character varying]::text[])),
  delivery_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (delivery_status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'delivered'::character varying, 'failed'::character varying]::text[])),
  delivered_at timestamp with time zone,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT alert_recipients_pkey PRIMARY KEY (id),
  CONSTRAINT alert_recipients_alert_id_fkey FOREIGN KEY (alert_id) REFERENCES public.alerts(id),
  CONSTRAINT alert_recipients_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id),
  CONSTRAINT alert_recipients_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id)
);
CREATE TABLE public.alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  content text NOT NULL,
  alert_type character varying NOT NULL CHECK (alert_type::text = ANY (ARRAY['sms'::character varying, 'email'::character varying, 'both'::character varying]::text[])),
  priority character varying NOT NULL DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'scheduled'::character varying, 'sending'::character varying, 'sent'::character varying, 'failed'::character varying]::text[])),
  scheduled_at timestamp with time zone,
  sent_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT alerts_pkey PRIMARY KEY (id),
  CONSTRAINT alerts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.app_configuration (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_name character varying NOT NULL DEFAULT 'Pison Academy'::character varying,
  school_logo_url text,
  primary_color character varying DEFAULT '#1E293B'::character varying,
  secondary_color character varying DEFAULT '#0EA5E9'::character varying,
  contact_email character varying,
  contact_phone character varying,
  address text,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  school_logo_alt_text character varying DEFAULT 'School Logo'::character varying,
  school_address text,
  school_phone character varying,
  school_email character varying,
  school_website character varying,
  school_motto text,
  academic_year character varying DEFAULT '2024-2025'::character varying,
  currency character varying DEFAULT 'XOF'::character varying,
  timezone character varying DEFAULT 'Africa/Douala'::character varying,
  language character varying DEFAULT 'en'::character varying,
  date_format character varying DEFAULT 'DD/MM/YYYY'::character varying,
  time_format character varying DEFAULT '24h'::character varying,
  created_by uuid,
  updated_by uuid,
  CONSTRAINT app_configuration_pkey PRIMARY KEY (id),
  CONSTRAINT app_configuration_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT app_configuration_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['quiz'::character varying, 'test'::character varying, 'exam'::character varying, 'assignment'::character varying, 'project'::character varying]::text[])),
  subject character varying NOT NULL,
  class_id character varying NOT NULL,
  class_name character varying,
  teacher_id uuid,
  total_marks integer NOT NULL,
  assessment_date date NOT NULL,
  due_date date,
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'published'::character varying, 'closed'::character varying]::text[])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  subject_id uuid,
  sub_branch_id uuid,
  CONSTRAINT assessments_pkey PRIMARY KEY (id),
  CONSTRAINT assessments_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id),
  CONSTRAINT assessments_sub_branch_id_fkey FOREIGN KEY (sub_branch_id) REFERENCES public.subject_sub_branches(id)
);
CREATE TABLE public.assignment_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id character varying NOT NULL UNIQUE,
  assignment_id uuid NOT NULL,
  student_id uuid NOT NULL,
  teacher_id uuid NOT NULL,
  submitted_text text,
  submission_file_url text,
  submission_file_name character varying,
  submission_file_size integer,
  submission_file_type character varying,
  marks_obtained numeric CHECK (marks_obtained IS NULL OR marks_obtained >= 0::numeric),
  percentage numeric CHECK (percentage IS NULL OR percentage >= 0::numeric AND percentage <= 100::numeric),
  grade_letter character varying,
  grade_point numeric,
  remarks text,
  feedback text,
  is_late boolean DEFAULT false,
  is_absent boolean DEFAULT false,
  is_excused boolean DEFAULT false,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  graded_at timestamp with time zone,
  status character varying DEFAULT 'submitted'::character varying CHECK (status::text = ANY (ARRAY['submitted'::character varying, 'graded'::character varying, 'late'::character varying, 'excused'::character varying]::text[])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assignment_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT assignment_submissions_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT assignment_submissions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id),
  CONSTRAINT assignment_submissions_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignment_id character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  description text,
  subject character varying NOT NULL,
  class_id character varying NOT NULL,
  teacher_id uuid NOT NULL,
  total_marks numeric NOT NULL,
  passing_marks numeric DEFAULT 50.0,
  weight_percentage numeric DEFAULT 100.0,
  assignment_file_url text,
  assignment_file_name character varying,
  assignment_file_size integer,
  assignment_file_type character varying,
  assigned_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date NOT NULL,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'published'::character varying, 'archived'::character varying]::text[])),
  instructions text,
  submission_type character varying DEFAULT 'file'::character varying CHECK (submission_type::text = ANY (ARRAY['file'::character varying, 'text'::character varying, 'both'::character varying]::text[])),
  allow_late_submission boolean DEFAULT false,
  late_penalty_percentage numeric DEFAULT 0.0 CHECK (late_penalty_percentage >= 0::numeric AND late_penalty_percentage <= 100::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assignments_pkey PRIMARY KEY (id),
  CONSTRAINT assignments_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.attendance_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  employee_name character varying NOT NULL,
  date date NOT NULL,
  check_in time without time zone,
  check_out time without time zone,
  status character varying NOT NULL DEFAULT 'present'::character varying CHECK (status::text = ANY (ARRAY['present'::character varying, 'absent'::character varying, 'late'::character varying, 'on-leave'::character varying, 'half-day'::character varying]::text[])),
  hours_worked numeric,
  notes text,
  marked_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_records_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.teachers(id),
  CONSTRAINT attendance_records_marked_by_fkey FOREIGN KEY (marked_by) REFERENCES public.users(id)
);
CREATE TABLE public.class_students (
  class_id uuid NOT NULL,
  student_id uuid NOT NULL,
  CONSTRAINT class_students_pkey PRIMARY KEY (class_id, student_id),
  CONSTRAINT class_students_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT class_students_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.class_subjects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  class_id uuid NOT NULL,
  subject_id uuid NOT NULL,
  is_trade_subject boolean NOT NULL DEFAULT false,
  academic_year character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  subject_name character varying,
  CONSTRAINT class_subjects_pkey PRIMARY KEY (id),
  CONSTRAINT class_subjects_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT class_subjects_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id)
);
CREATE TABLE public.class_teachers (
  class_id uuid NOT NULL,
  teacher_row_id uuid NOT NULL,
  CONSTRAINT class_teachers_pkey PRIMARY KEY (class_id, teacher_row_id),
  CONSTRAINT class_teachers_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT class_teachers_teacher_row_id_fkey FOREIGN KEY (teacher_row_id) REFERENCES public.teachers(id)
);
CREATE TABLE public.classes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  level character varying,
  section character varying,
  subsystem character varying CHECK (subsystem::text = ANY (ARRAY['english'::character varying, 'french'::character varying]::text[])),
  subject character varying,
  student_count integer DEFAULT 0,
  schedule text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  class_teacher_id uuid,
  academic_year character varying,
  capacity integer DEFAULT 40,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  class_name character varying,
  class_level character varying,
  stream character varying,
  current_enrollment integer DEFAULT 0,
  CONSTRAINT classes_pkey PRIMARY KEY (id),
  CONSTRAINT classes_class_teacher_id_fkey FOREIGN KEY (class_teacher_id) REFERENCES public.teachers(id)
);
CREATE TABLE public.emergency_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  name character varying NOT NULL,
  phone character varying NOT NULL,
  relationship character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT emergency_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT emergency_contacts_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.exam_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  examination_id uuid NOT NULL,
  student_id uuid,
  student_name character varying NOT NULL,
  subject character varying NOT NULL,
  marks_obtained numeric NOT NULL,
  total_marks integer NOT NULL,
  percentage numeric NOT NULL,
  grade character varying,
  remarks text,
  date_recorded timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT exam_results_pkey PRIMARY KEY (id),
  CONSTRAINT exam_results_examination_id_fkey FOREIGN KEY (examination_id) REFERENCES public.examinations(id),
  CONSTRAINT exam_results_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.examinations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['internal'::character varying, 'external'::character varying, 'mock'::character varying, 'continuous_assessment'::character varying]::text[])),
  exam_board character varying NOT NULL,
  subsystem character varying NOT NULL CHECK (subsystem::text = ANY (ARRAY['english'::character varying, 'french'::character varying]::text[])),
  branch character varying NOT NULL CHECK (branch::text = ANY (ARRAY['grammar'::character varying, 'technical'::character varying, 'commercial'::character varying]::text[])),
  level character varying NOT NULL,
  subjects ARRAY NOT NULL,
  start_date date,
  end_date date,
  duration integer NOT NULL,
  total_marks integer NOT NULL,
  passing_marks integer NOT NULL,
  venue character varying NOT NULL,
  instructions text,
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'scheduled'::character varying, 'ongoing'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  enrolled_students integer DEFAULT 0,
  completed_students integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  grading_system jsonb,
  CONSTRAINT examinations_pkey PRIMARY KEY (id),
  CONSTRAINT examinations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.expenditures (
  id text NOT NULL,
  title text NOT NULL,
  description text,
  category character varying NOT NULL,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'XOF'::character varying,
  payment_method character varying,
  payment_date date NOT NULL,
  vendor text NOT NULL,
  vendor_contact text,
  receipt_number text,
  invoice_number text,
  status character varying DEFAULT 'pending'::character varying,
  approved_by text,
  approved_at timestamp with time zone,
  academic_year character varying,
  term character varying,
  department text,
  budget_category character varying,
  notes text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expenditures_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fee_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  code character varying UNIQUE,
  description text,
  is_active boolean DEFAULT true,
  is_mandatory boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fee_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fee_structure_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  fee_structure_id uuid NOT NULL,
  fee_category_id uuid,
  amount numeric NOT NULL,
  is_optional boolean DEFAULT false,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fee_structure_items_pkey PRIMARY KEY (id),
  CONSTRAINT fee_structure_items_fee_structure_id_fkey FOREIGN KEY (fee_structure_id) REFERENCES public.fee_structures(id),
  CONSTRAINT fee_structure_items_fee_category_id_fkey FOREIGN KEY (fee_category_id) REFERENCES public.fee_categories(id)
);
CREATE TABLE public.fee_structures (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  subsystem character varying NOT NULL CHECK (subsystem::text = ANY (ARRAY['english'::character varying, 'french'::character varying]::text[])),
  level character varying NOT NULL,
  branch character varying NOT NULL CHECK (branch::text = ANY (ARRAY['grammar'::character varying, 'technical'::character varying, 'commercial'::character varying]::text[])),
  amount numeric NOT NULL,
  due_date date NOT NULL,
  term character varying NOT NULL CHECK (term::text = ANY (ARRAY['first'::character varying, 'second'::character varying, 'third'::character varying]::text[])),
  academic_year character varying NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  class_id uuid,
  CONSTRAINT fee_structures_pkey PRIMARY KEY (id),
  CONSTRAINT fee_structures_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fee_structures_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.grades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid NOT NULL,
  student_id uuid NOT NULL,
  student_name character varying,
  marks_obtained numeric NOT NULL,
  percentage numeric,
  grade_letter character varying,
  remarks text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT grades_pkey PRIMARY KEY (id),
  CONSTRAINT grades_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT grades_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.leave_balances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  year integer NOT NULL CHECK (year >= 2020 AND year <= 2100),
  annual_leave_total integer DEFAULT 30 CHECK (annual_leave_total >= 0),
  annual_leave_used integer DEFAULT 0 CHECK (annual_leave_used >= 0),
  annual_leave_remaining integer DEFAULT 30 CHECK (annual_leave_remaining >= 0),
  sick_leave_total integer DEFAULT 14 CHECK (sick_leave_total >= 0),
  sick_leave_used integer DEFAULT 0 CHECK (sick_leave_used >= 0),
  sick_leave_remaining integer DEFAULT 14 CHECK (sick_leave_remaining >= 0),
  study_leave_total integer DEFAULT 0 CHECK (study_leave_total >= 0),
  study_leave_used integer DEFAULT 0 CHECK (study_leave_used >= 0),
  study_leave_remaining integer DEFAULT 0 CHECK (study_leave_remaining >= 0),
  compassionate_leave_total integer DEFAULT 5 CHECK (compassionate_leave_total >= 0),
  compassionate_leave_used integer DEFAULT 0 CHECK (compassionate_leave_used >= 0),
  compassionate_leave_remaining integer DEFAULT 5 CHECK (compassionate_leave_remaining >= 0),
  carried_forward_days integer DEFAULT 0 CHECK (carried_forward_days >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_balances_pkey PRIMARY KEY (id),
  CONSTRAINT leave_balances_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.teachers(id)
);
CREATE TABLE public.leave_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  employee_name character varying NOT NULL,
  leave_type character varying NOT NULL CHECK (leave_type::text = ANY (ARRAY['annual'::character varying, 'sick'::character varying, 'maternity'::character varying, 'paternity'::character varying, 'unpaid'::character varying, 'study'::character varying, 'compassionate'::character varying]::text[])),
  start_date date NOT NULL,
  end_date date NOT NULL,
  total_days integer NOT NULL CHECK (total_days > 0),
  reason text NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])),
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT leave_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.teachers(id),
  CONSTRAINT leave_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.levels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  subsystem character varying NOT NULL CHECK (subsystem::text = ANY (ARRAY['english'::character varying, 'french'::character varying]::text[])),
  branch character varying NOT NULL CHECK (branch::text = ANY (ARRAY['grammar'::character varying, 'technical'::character varying, 'commercial'::character varying]::text[])),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT levels_pkey PRIMARY KEY (id),
  CONSTRAINT levels_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.medical_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  blood_group character varying,
  allergies text,
  medical_conditions text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT medical_info_pkey PRIMARY KEY (id),
  CONSTRAINT medical_info_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  recipient_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text DEFAULT 'info'::text CHECK (type = ANY (ARRAY['info'::text, 'success'::text, 'warning'::text, 'error'::text])),
  read boolean DEFAULT false,
  data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES auth.users(id)
);
CREATE TABLE public.parents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parent_code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  email character varying,
  phone character varying,
  address text,
  occupation character varying,
  relationship character varying CHECK (relationship::text = ANY (ARRAY['father'::character varying, 'mother'::character varying, 'guardian'::character varying, 'other'::character varying]::text[])),
  student_id character varying NOT NULL,
  tenant_id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT parents_pkey PRIMARY KEY (id),
  CONSTRAINT parents_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public."Tenant"(id)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  code character varying NOT NULL UNIQUE,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_plan_installments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payment_plan_id uuid NOT NULL,
  installment_number integer NOT NULL,
  amount numeric NOT NULL,
  due_date date NOT NULL,
  paid_date date,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'overdue'::character varying]::text[])),
  payment_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_plan_installments_pkey PRIMARY KEY (id),
  CONSTRAINT payment_plan_installments_payment_plan_id_fkey FOREIGN KEY (payment_plan_id) REFERENCES public.payment_plans(id),
  CONSTRAINT payment_plan_installments_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.payment_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  fee_structure_id uuid NOT NULL,
  total_amount numeric NOT NULL,
  amount_paid numeric DEFAULT 0,
  balance numeric NOT NULL,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'completed'::character varying, 'defaulted'::character varying]::text[])),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_plans_pkey PRIMARY KEY (id),
  CONSTRAINT payment_plans_fee_structure_id_fkey FOREIGN KEY (fee_structure_id) REFERENCES public.fee_structures(id),
  CONSTRAINT payment_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid,
  fee_structure_id uuid,
  amount numeric NOT NULL,
  payment_date date NOT NULL,
  payment_method character varying,
  payment_method_id uuid,
  receipt_number character varying UNIQUE,
  paid_by character varying,
  received_by uuid,
  academic_year character varying,
  term character varying,
  status character varying DEFAULT 'completed'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'partial'::character varying, 'completed'::character varying, 'overdue'::character varying]::text[])),
  notes text,
  description text,
  reference_number character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT payments_fee_structure_id_fkey FOREIGN KEY (fee_structure_id) REFERENCES public.fee_structures(id),
  CONSTRAINT payments_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id),
  CONSTRAINT payments_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.users(id)
);
CREATE TABLE public.payroll_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  employee_name character varying NOT NULL,
  month character varying NOT NULL,
  year integer NOT NULL CHECK (year >= 2020 AND year <= 2100),
  basic_salary numeric NOT NULL CHECK (basic_salary >= 0::numeric),
  allowances numeric DEFAULT 0 CHECK (allowances >= 0::numeric),
  bonuses numeric DEFAULT 0 CHECK (bonuses >= 0::numeric),
  deductions numeric DEFAULT 0 CHECK (deductions >= 0::numeric),
  tax numeric DEFAULT 0 CHECK (tax >= 0::numeric),
  net_salary numeric NOT NULL CHECK (net_salary >= 0::numeric),
  payment_date date,
  payment_method character varying NOT NULL DEFAULT 'bank-transfer'::character varying CHECK (payment_method::text = ANY (ARRAY['bank-transfer'::character varying, 'cash'::character varying, 'cheque'::character varying, 'mobile-money'::character varying]::text[])),
  payment_reference character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processed'::character varying, 'paid'::character varying, 'cancelled'::character varying]::text[])),
  notes text,
  processed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_records_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.teachers(id),
  CONSTRAINT payroll_records_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.users(id)
);
CREATE TABLE public.performance_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  employee_name character varying NOT NULL,
  review_period character varying NOT NULL,
  review_date date NOT NULL,
  reviewer_id uuid NOT NULL,
  reviewer_name character varying NOT NULL,
  overall_rating numeric CHECK (overall_rating >= 1::numeric AND overall_rating <= 5::numeric),
  teaching_effectiveness numeric CHECK (teaching_effectiveness >= 1::numeric AND teaching_effectiveness <= 5::numeric),
  classroom_management numeric CHECK (classroom_management >= 1::numeric AND classroom_management <= 5::numeric),
  student_engagement numeric CHECK (student_engagement >= 1::numeric AND student_engagement <= 5::numeric),
  professionalism numeric CHECK (professionalism >= 1::numeric AND professionalism <= 5::numeric),
  collaboration numeric CHECK (collaboration >= 1::numeric AND collaboration <= 5::numeric),
  strengths text,
  areas_for_improvement text,
  goals text,
  comments text,
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'completed'::character varying, 'acknowledged'::character varying]::text[])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT performance_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT performance_reviews_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.teachers(id),
  CONSTRAINT performance_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id)
);
CREATE TABLE public.sales (
  id character varying NOT NULL,
  student_id character varying NOT NULL,
  student_name character varying NOT NULL,
  item_type character varying NOT NULL CHECK (item_type::text = ANY (ARRAY['pullover'::character varying, 'sport_wear'::character varying, 'uniform'::character varying, 't_shirt'::character varying]::text[])),
  item_name character varying NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  sale_date date NOT NULL DEFAULT CURRENT_DATE,
  status character varying NOT NULL DEFAULT 'completed'::character varying CHECK (status::text = ANY (ARRAY['completed'::character varying, 'pending'::character varying, 'cancelled'::character varying]::text[])),
  notes text,
  created_by character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sequence_configurations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  academic_year character varying NOT NULL UNIQUE,
  term character varying,
  use_fixed_sequences boolean DEFAULT true,
  default_max_marks integer DEFAULT 20,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  total_sequences integer NOT NULL DEFAULT 6 CHECK (total_sequences >= 5 AND total_sequences <= 6),
  term_sequence_counts jsonb,
  CONSTRAINT sequence_configurations_pkey PRIMARY KEY (id),
  CONSTRAINT sequence_configurations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.student_fee_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid,
  fee_structure_id uuid,
  academic_year character varying NOT NULL,
  term character varying NOT NULL,
  total_amount numeric NOT NULL,
  amount_paid numeric DEFAULT 0,
  balance_amount numeric NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'partial'::character varying, 'paid'::character varying, 'overdue'::character varying]::text[])),
  due_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_fee_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT student_fee_assignments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT student_fee_assignments_fee_structure_id_fkey FOREIGN KEY (fee_structure_id) REFERENCES public.fee_structures(id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id character varying NOT NULL UNIQUE,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  middle_name character varying,
  email character varying,
  phone character varying,
  date_of_birth date,
  gender character varying CHECK (gender::text = ANY (ARRAY['male'::character varying, 'female'::character varying, 'other'::character varying]::text[])),
  place_of_birth character varying,
  nationality character varying DEFAULT 'Cameroonian'::character varying,
  religion character varying,
  address text,
  city character varying,
  region character varying,
  subsystem character varying CHECK (subsystem::text = ANY (ARRAY['english'::character varying, 'french'::character varying]::text[])),
  branch character varying CHECK (branch::text = ANY (ARRAY['grammar'::character varying, 'technical'::character varying, 'commercial'::character varying]::text[])),
  class character varying,
  previous_school character varying,
  previous_class character varying,
  is_new_student boolean DEFAULT true,
  total_fees numeric DEFAULT 0,
  paid_fees numeric DEFAULT 0,
  fees_status character varying DEFAULT 'pending'::character varying,
  enrollment_status character varying DEFAULT 'pending'::character varying,
  academic_year character varying,
  status character varying DEFAULT 'active'::character varying,
  enrollment_date date DEFAULT CURRENT_DATE,
  class_id character varying,
  class_name character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  matricule_number character varying,
  CONSTRAINT students_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subject_branches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL,
  branch_name character varying NOT NULL,
  branch_code character varying,
  description text,
  weight_percentage numeric CHECK (weight_percentage >= 0::numeric AND weight_percentage <= 100::numeric),
  is_optional boolean DEFAULT false,
  is_active boolean DEFAULT true,
  academic_year character varying,
  term character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subject_branches_pkey PRIMARY KEY (id),
  CONSTRAINT subject_branches_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id)
);
CREATE TABLE public.subject_sub_branches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL,
  name character varying NOT NULL,
  coefficient numeric NOT NULL DEFAULT 1.0 CHECK (coefficient > 0::numeric),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subject_sub_branches_pkey PRIMARY KEY (id),
  CONSTRAINT subject_sub_branches_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id)
);
CREATE TABLE public.subjects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  code character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  has_sub_branches boolean NOT NULL DEFAULT false,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  coefficient numeric NOT NULL DEFAULT 1.0 CHECK (coefficient > 0::numeric),
  subject_groupings ARRAY NOT NULL DEFAULT '{}'::text[] CHECK (array_length(subject_groupings, 1) IS NULL OR subject_groupings <@ ARRAY['languages'::text, 'related_trade_subjects'::text, 'trade_subjects'::text, 'others'::text]),
  CONSTRAINT subjects_pkey PRIMARY KEY (id)
);
CREATE TABLE public.teacher_branch_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  class_id uuid NOT NULL,
  academic_year character varying NOT NULL,
  term character varying NOT NULL,
  is_primary_teacher boolean DEFAULT false,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'completed'::character varying]::text[])),
  assigned_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT teacher_branch_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_branch_assignments_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id),
  CONSTRAINT teacher_branch_assignments_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.subject_branches(id),
  CONSTRAINT teacher_branch_assignments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.teacher_subjects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  subject_name character varying NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  subject_id uuid,
  sub_branch_id uuid,
  assignment_type character varying DEFAULT 'main_subject'::character varying CHECK (assignment_type::text = ANY (ARRAY['main_subject'::character varying, 'sub_branch'::character varying]::text[])),
  CONSTRAINT teacher_subjects_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_subjects_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id),
  CONSTRAINT teacher_subjects_sub_branch_id_fkey FOREIGN KEY (sub_branch_id) REFERENCES public.subject_sub_branches(id),
  CONSTRAINT teacher_subjects_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.teachers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id character varying NOT NULL UNIQUE,
  title character varying,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  date_of_birth date,
  gender character varying CHECK (gender::text = ANY (ARRAY['male'::character varying, 'female'::character varying, 'other'::character varying]::text[])),
  nationality character varying,
  id_number character varying,
  address text,
  city character varying,
  region character varying,
  subsystem character varying CHECK (subsystem::text = ANY (ARRAY['english'::character varying, 'french'::character varying]::text[])),
  subjects ARRAY DEFAULT '{}'::text[],
  classes ARRAY DEFAULT '{}'::text[],
  qualifications ARRAY DEFAULT '{}'::text[],
  experience text,
  employment_type character varying CHECK (employment_type::text = ANY (ARRAY['full-time'::character varying, 'part-time'::character varying, 'contract'::character varying, 'temporary'::character varying]::text[])),
  salary numeric DEFAULT 0,
  start_date date,
  emergency_contact_name character varying,
  emergency_contact_relationship character varying,
  emergency_contact_phone character varying,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying, 'terminated'::character varying, 'retired'::character varying]::text[])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  end_date date,
  contract_renewal_date date,
  department character varying,
  specialization character varying,
  emergency_contact_email character varying,
  emergency_contact_address text,
  postal_code character varying,
  country character varying DEFAULT 'Cameroon'::character varying,
  is_verified boolean DEFAULT false,
  profile_completed boolean DEFAULT false,
  CONSTRAINT teachers_pkey PRIMARY KEY (id),
  CONSTRAINT teachers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.timetable_classes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  class_name character varying NOT NULL,
  level character varying,
  section character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT timetable_classes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.timetable_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  class_id uuid,
  teacher_id uuid,
  room_id uuid,
  subject_id uuid,
  weekday character varying CHECK (weekday::text = ANY (ARRAY['Mon'::character varying, 'Tue'::character varying, 'Wed'::character varying, 'Thu'::character varying, 'Fri'::character varying, 'Sat'::character varying]::text[])),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT timetable_periods_pkey PRIMARY KEY (id),
  CONSTRAINT timetable_periods_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.timetable_classes(id),
  CONSTRAINT timetable_periods_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.timetable_teachers(id),
  CONSTRAINT timetable_periods_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.timetable_rooms(id),
  CONSTRAINT timetable_periods_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.timetable_subjects(id)
);
CREATE TABLE public.timetable_rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_name character varying NOT NULL,
  capacity integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT timetable_rooms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.timetable_subjects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_name character varying NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT timetable_subjects_pkey PRIMARY KEY (id)
);
CREATE TABLE public.timetable_teachers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_name character varying NOT NULL,
  subject character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT timetable_teachers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action character varying NOT NULL,
  details text,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT user_activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role_specific_id character varying UNIQUE,
  subsystem character varying CHECK (subsystem::text = ANY (ARRAY['english'::character varying, 'french'::character varying]::text[])),
  branch character varying CHECK (branch::text = ANY (ARRAY['grammar'::character varying, 'technical'::character varying, 'commercial'::character varying]::text[])),
  class_name character varying,
  occupation character varying,
  relationship character varying CHECK (relationship::text = ANY (ARRAY['father'::character varying, 'mother'::character varying, 'guardian'::character varying, 'other'::character varying]::text[])),
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  emergency_contact_relationship character varying,
  blood_group character varying,
  allergies text,
  medical_conditions text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  name character varying NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['admin'::character varying, 'teacher'::character varying, 'student'::character varying, 'parent'::character varying, 'bursar'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying]::text[])),
  avatar_url text,
  phone character varying,
  address text,
  date_of_birth date,
  gender character varying CHECK (gender::text = ANY (ARRAY['male'::character varying, 'female'::character varying, 'other'::character varying]::text[])),
  permissions ARRAY,
  has_default_password boolean NOT NULL DEFAULT true,
  password_last_changed timestamp with time zone NOT NULL DEFAULT now(),
  password_expiry_date timestamp with time zone,
  last_login timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);