-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.AcademicCalendarMilestone (
  id text NOT NULL,
  tenantId text NOT NULL,
  academicYearId text NOT NULL,
  kind USER-DEFINED NOT NULL,
  onDate date NOT NULL,
  termId text,
  labelEn text,
  labelFr text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT AcademicCalendarMilestone_pkey PRIMARY KEY (id),
  CONSTRAINT AcademicCalendarMilestone_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT AcademicCalendarMilestone_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(id),
  CONSTRAINT AcademicCalendarMilestone_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT AcademicCalendarMilestone_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT AcademicCalendarMilestone_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT AcademicCalendarMilestone_termId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Term(id),
  CONSTRAINT AcademicCalendarMilestone_termId_tenantId_fkey FOREIGN KEY (termId) REFERENCES public.Term(id),
  CONSTRAINT AcademicCalendarMilestone_termId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Term(tenantId),
  CONSTRAINT AcademicCalendarMilestone_termId_tenantId_fkey FOREIGN KEY (termId) REFERENCES public.Term(tenantId)
);
CREATE TABLE public.AcademicYear (
  id text NOT NULL,
  tenantId text NOT NULL,
  label text NOT NULL CHECK (length(btrim(label)) > 0),
  startsOn date NOT NULL,
  endsOn date NOT NULL,
  isCurrent boolean NOT NULL DEFAULT false,
  isActive boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  enrollmentOpensAt date,
  enrollmentClosesAt date,
  timetablePublishedAt timestamp without time zone,
  timetablePublishedByUserId text,
  CONSTRAINT AcademicYear_pkey PRIMARY KEY (id),
  CONSTRAINT AcademicYear_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT AcademicYear_timetablePublishedByUserId_fkey FOREIGN KEY (timetablePublishedByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.Account (
  id text NOT NULL,
  userId text NOT NULL,
  type text NOT NULL,
  provider text NOT NULL,
  providerAccountId text NOT NULL,
  refresh_token text,
  access_token text,
  expires_at integer,
  token_type text,
  scope text,
  id_token text,
  session_state text,
  CONSTRAINT Account_pkey PRIMARY KEY (id),
  CONSTRAINT Account_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.AttendanceRecord (
  id text NOT NULL,
  tenantId text NOT NULL,
  attendanceSessionId text NOT NULL,
  studentProfileId text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'ABSENT'::"AttendanceRecordStatus",
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT AttendanceRecord_pkey PRIMARY KEY (id),
  CONSTRAINT AttendanceRecord_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT AttendanceRecord_attendanceSessionId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AttendanceSession(id),
  CONSTRAINT AttendanceRecord_attendanceSessionId_tenantId_fkey FOREIGN KEY (attendanceSessionId) REFERENCES public.AttendanceSession(id),
  CONSTRAINT AttendanceRecord_attendanceSessionId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AttendanceSession(tenantId),
  CONSTRAINT AttendanceRecord_attendanceSessionId_tenantId_fkey FOREIGN KEY (attendanceSessionId) REFERENCES public.AttendanceSession(tenantId),
  CONSTRAINT AttendanceRecord_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(id),
  CONSTRAINT AttendanceRecord_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(id),
  CONSTRAINT AttendanceRecord_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT AttendanceRecord_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(tenantId)
);
CREATE TABLE public.AttendanceSession (
  id text NOT NULL,
  tenantId text NOT NULL,
  academicYearId text NOT NULL,
  courseId text NOT NULL,
  timetableSlotId text,
  sessionDate date NOT NULL,
  label text,
  createdByUserId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT AttendanceSession_pkey PRIMARY KEY (id),
  CONSTRAINT AttendanceSession_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT AttendanceSession_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(id),
  CONSTRAINT AttendanceSession_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT AttendanceSession_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT AttendanceSession_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT AttendanceSession_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(id),
  CONSTRAINT AttendanceSession_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(id),
  CONSTRAINT AttendanceSession_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(tenantId),
  CONSTRAINT AttendanceSession_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(tenantId),
  CONSTRAINT AttendanceSession_timetableSlotId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.TimetableSlot(id),
  CONSTRAINT AttendanceSession_timetableSlotId_tenantId_fkey FOREIGN KEY (timetableSlotId) REFERENCES public.TimetableSlot(id),
  CONSTRAINT AttendanceSession_timetableSlotId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.TimetableSlot(tenantId),
  CONSTRAINT AttendanceSession_timetableSlotId_tenantId_fkey FOREIGN KEY (timetableSlotId) REFERENCES public.TimetableSlot(tenantId),
  CONSTRAINT AttendanceSession_createdByUserId_fkey FOREIGN KEY (createdByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.Course (
  id text NOT NULL,
  tenantId text NOT NULL,
  code text NOT NULL CHECK (length(btrim(code)) > 0),
  nameEn text NOT NULL CHECK (length(btrim("nameEn")) > 0),
  nameFr text NOT NULL CHECK (length(btrim("nameFr")) > 0),
  credits integer NOT NULL CHECK (credits > 0),
  hours integer NOT NULL CHECK (hours > 0),
  specialtyId text NOT NULL,
  levelId text NOT NULL,
  termId text NOT NULL,
  deactivatedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Course_pkey PRIMARY KEY (id),
  CONSTRAINT Course_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT Course_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(id),
  CONSTRAINT Course_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(id),
  CONSTRAINT Course_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT Course_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT Course_levelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(id),
  CONSTRAINT Course_levelId_tenantId_fkey FOREIGN KEY (levelId) REFERENCES public.Level(id),
  CONSTRAINT Course_levelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(tenantId),
  CONSTRAINT Course_levelId_tenantId_fkey FOREIGN KEY (levelId) REFERENCES public.Level(tenantId),
  CONSTRAINT Course_termId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Term(id),
  CONSTRAINT Course_termId_tenantId_fkey FOREIGN KEY (termId) REFERENCES public.Term(id),
  CONSTRAINT Course_termId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Term(tenantId),
  CONSTRAINT Course_termId_tenantId_fkey FOREIGN KEY (termId) REFERENCES public.Term(tenantId)
);
CREATE TABLE public.CourseAssignment (
  id text NOT NULL,
  tenantId text NOT NULL,
  academicYearId text NOT NULL,
  courseId text NOT NULL,
  staffProfileId text NOT NULL,
  teachesPrimaryHome boolean NOT NULL DEFAULT true,
  isLead boolean NOT NULL DEFAULT false,
  notes text CHECK (notes IS NULL OR length(btrim(notes)) > 0),
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT CourseAssignment_pkey PRIMARY KEY (id),
  CONSTRAINT CourseAssignment_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT CourseAssignment_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(id),
  CONSTRAINT CourseAssignment_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT CourseAssignment_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT CourseAssignment_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT CourseAssignment_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(id),
  CONSTRAINT CourseAssignment_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(id),
  CONSTRAINT CourseAssignment_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(tenantId),
  CONSTRAINT CourseAssignment_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(tenantId),
  CONSTRAINT CourseAssignment_staffProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StaffProfile(id),
  CONSTRAINT CourseAssignment_staffProfileId_tenantId_fkey FOREIGN KEY (staffProfileId) REFERENCES public.StaffProfile(id),
  CONSTRAINT CourseAssignment_staffProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StaffProfile(tenantId),
  CONSTRAINT CourseAssignment_staffProfileId_tenantId_fkey FOREIGN KEY (staffProfileId) REFERENCES public.StaffProfile(tenantId)
);
CREATE TABLE public.CourseAssignmentOffering (
  id text NOT NULL,
  tenantId text NOT NULL,
  courseAssignmentId text NOT NULL,
  offeringId text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CourseAssignmentOffering_pkey PRIMARY KEY (id),
  CONSTRAINT CourseAssignmentOffering_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT CourseAssignmentOffering_courseAssignmentId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.CourseAssignment(id),
  CONSTRAINT CourseAssignmentOffering_courseAssignmentId_tenantId_fkey FOREIGN KEY (courseAssignmentId) REFERENCES public.CourseAssignment(id),
  CONSTRAINT CourseAssignmentOffering_courseAssignmentId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.CourseAssignment(tenantId),
  CONSTRAINT CourseAssignmentOffering_courseAssignmentId_tenantId_fkey FOREIGN KEY (courseAssignmentId) REFERENCES public.CourseAssignment(tenantId),
  CONSTRAINT CourseAssignmentOffering_offeringId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.CourseSpecialtyOffering(id),
  CONSTRAINT CourseAssignmentOffering_offeringId_tenantId_fkey FOREIGN KEY (offeringId) REFERENCES public.CourseSpecialtyOffering(id),
  CONSTRAINT CourseAssignmentOffering_offeringId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.CourseSpecialtyOffering(tenantId),
  CONSTRAINT CourseAssignmentOffering_offeringId_tenantId_fkey FOREIGN KEY (offeringId) REFERENCES public.CourseSpecialtyOffering(tenantId)
);
CREATE TABLE public.CourseDiscussionPost (
  id text NOT NULL,
  tenantId text NOT NULL,
  threadId text NOT NULL,
  authorUserId text NOT NULL,
  body text NOT NULL,
  hiddenAt timestamp without time zone,
  hiddenByUserId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CourseDiscussionPost_pkey PRIMARY KEY (id),
  CONSTRAINT CourseDiscussionPost_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT CourseDiscussionPost_threadId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.CourseDiscussionThread(id),
  CONSTRAINT CourseDiscussionPost_threadId_tenantId_fkey FOREIGN KEY (threadId) REFERENCES public.CourseDiscussionThread(id),
  CONSTRAINT CourseDiscussionPost_threadId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.CourseDiscussionThread(tenantId),
  CONSTRAINT CourseDiscussionPost_threadId_tenantId_fkey FOREIGN KEY (threadId) REFERENCES public.CourseDiscussionThread(tenantId),
  CONSTRAINT CourseDiscussionPost_authorUserId_fkey FOREIGN KEY (authorUserId) REFERENCES public.User(id),
  CONSTRAINT CourseDiscussionPost_hiddenByUserId_fkey FOREIGN KEY (hiddenByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.CourseDiscussionThread (
  id text NOT NULL,
  tenantId text NOT NULL,
  courseId text NOT NULL,
  academicYearId text NOT NULL,
  locked boolean NOT NULL DEFAULT false,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CourseDiscussionThread_pkey PRIMARY KEY (id),
  CONSTRAINT CourseDiscussionThread_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT CourseDiscussionThread_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(id),
  CONSTRAINT CourseDiscussionThread_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(id),
  CONSTRAINT CourseDiscussionThread_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(tenantId),
  CONSTRAINT CourseDiscussionThread_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(tenantId),
  CONSTRAINT CourseDiscussionThread_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(id),
  CONSTRAINT CourseDiscussionThread_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT CourseDiscussionThread_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT CourseDiscussionThread_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(tenantId)
);
CREATE TABLE public.CourseMark (
  id text NOT NULL,
  tenantId text NOT NULL,
  examSessionId text NOT NULL,
  studentProfileId text NOT NULL,
  courseId text NOT NULL,
  caScore numeric,
  examScore numeric,
  totalScore numeric,
  isResitEligible boolean NOT NULL DEFAULT false,
  enteredByUserId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT CourseMark_pkey PRIMARY KEY (id),
  CONSTRAINT CourseMark_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT CourseMark_examSessionId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.ExamSession(id),
  CONSTRAINT CourseMark_examSessionId_tenantId_fkey FOREIGN KEY (examSessionId) REFERENCES public.ExamSession(id),
  CONSTRAINT CourseMark_examSessionId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.ExamSession(tenantId),
  CONSTRAINT CourseMark_examSessionId_tenantId_fkey FOREIGN KEY (examSessionId) REFERENCES public.ExamSession(tenantId),
  CONSTRAINT CourseMark_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(id),
  CONSTRAINT CourseMark_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(id),
  CONSTRAINT CourseMark_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT CourseMark_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT CourseMark_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(id),
  CONSTRAINT CourseMark_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(id),
  CONSTRAINT CourseMark_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(tenantId),
  CONSTRAINT CourseMark_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(tenantId),
  CONSTRAINT CourseMark_enteredByUserId_fkey FOREIGN KEY (enteredByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.CourseSpecialtyOffering (
  id text NOT NULL,
  tenantId text NOT NULL,
  courseId text NOT NULL,
  specialtyId text NOT NULL,
  levelId text NOT NULL,
  termId text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CourseSpecialtyOffering_pkey PRIMARY KEY (id),
  CONSTRAINT CourseSpecialtyOffering_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT CourseSpecialtyOffering_termId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Term(id),
  CONSTRAINT CourseSpecialtyOffering_termId_tenantId_fkey FOREIGN KEY (termId) REFERENCES public.Term(id),
  CONSTRAINT CourseSpecialtyOffering_termId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Term(tenantId),
  CONSTRAINT CourseSpecialtyOffering_termId_tenantId_fkey FOREIGN KEY (termId) REFERENCES public.Term(tenantId),
  CONSTRAINT CourseSpecialtyOffering_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(id),
  CONSTRAINT CourseSpecialtyOffering_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(id),
  CONSTRAINT CourseSpecialtyOffering_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(tenantId),
  CONSTRAINT CourseSpecialtyOffering_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(tenantId),
  CONSTRAINT CourseSpecialtyOffering_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(id),
  CONSTRAINT CourseSpecialtyOffering_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(id),
  CONSTRAINT CourseSpecialtyOffering_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT CourseSpecialtyOffering_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT CourseSpecialtyOffering_levelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(id),
  CONSTRAINT CourseSpecialtyOffering_levelId_tenantId_fkey FOREIGN KEY (levelId) REFERENCES public.Level(id),
  CONSTRAINT CourseSpecialtyOffering_levelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(tenantId),
  CONSTRAINT CourseSpecialtyOffering_levelId_tenantId_fkey FOREIGN KEY (levelId) REFERENCES public.Level(tenantId)
);
CREATE TABLE public.CourseworkSubmission (
  id text NOT NULL,
  tenantId text NOT NULL,
  taskId text NOT NULL,
  studentProfileId text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::"CourseworkSubmissionStatus",
  fileStorageKey text,
  originalFileName text,
  mimeType text,
  fileSize integer,
  submittedAt timestamp without time zone,
  confirmedScore numeric,
  confirmedAt timestamp without time zone,
  confirmedByUserId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT CourseworkSubmission_pkey PRIMARY KEY (id),
  CONSTRAINT CourseworkSubmission_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT CourseworkSubmission_taskId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.CourseworkTask(id),
  CONSTRAINT CourseworkSubmission_taskId_tenantId_fkey FOREIGN KEY (taskId) REFERENCES public.CourseworkTask(id),
  CONSTRAINT CourseworkSubmission_taskId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.CourseworkTask(tenantId),
  CONSTRAINT CourseworkSubmission_taskId_tenantId_fkey FOREIGN KEY (taskId) REFERENCES public.CourseworkTask(tenantId),
  CONSTRAINT CourseworkSubmission_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(id),
  CONSTRAINT CourseworkSubmission_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(id),
  CONSTRAINT CourseworkSubmission_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT CourseworkSubmission_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT CourseworkSubmission_confirmedByUserId_fkey FOREIGN KEY (confirmedByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.CourseworkTask (
  id text NOT NULL,
  tenantId text NOT NULL,
  academicYearId text NOT NULL,
  courseId text NOT NULL,
  titleEn text NOT NULL,
  titleFr text NOT NULL,
  descriptionEn text,
  descriptionFr text,
  dueAt timestamp without time zone NOT NULL,
  maxScore numeric NOT NULL,
  isPublished boolean NOT NULL DEFAULT false,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT CourseworkTask_pkey PRIMARY KEY (id),
  CONSTRAINT CourseworkTask_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT CourseworkTask_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(id),
  CONSTRAINT CourseworkTask_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT CourseworkTask_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT CourseworkTask_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT CourseworkTask_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(id),
  CONSTRAINT CourseworkTask_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(id),
  CONSTRAINT CourseworkTask_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(tenantId),
  CONSTRAINT CourseworkTask_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(tenantId)
);
CREATE TABLE public.DataExportJob (
  id text NOT NULL,
  tenantId text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"DataExportJobStatus",
  format text NOT NULL DEFAULT 'json'::text,
  artifactStorageKey text,
  errorMessage text,
  createdByUserId text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completedAt timestamp without time zone,
  CONSTRAINT DataExportJob_pkey PRIMARY KEY (id),
  CONSTRAINT DataExportJob_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT DataExportJob_createdByUserId_fkey FOREIGN KEY (createdByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.Department (
  id text NOT NULL,
  tenantId text NOT NULL,
  code text NOT NULL CHECK (length(btrim(code)) > 0),
  nameEn text NOT NULL CHECK (length(btrim("nameEn")) > 0),
  nameFr text NOT NULL CHECK (length(btrim("nameFr")) > 0),
  isPublished boolean NOT NULL DEFAULT false,
  publishedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Department_pkey PRIMARY KEY (id),
  CONSTRAINT Department_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id)
);
CREATE TABLE public.EnrollmentApplication (
  id text NOT NULL,
  tenantId text NOT NULL,
  kind USER-DEFINED NOT NULL DEFAULT 'NEW'::"EnrollmentApplicationKind",
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"EnrollmentApplicationStatus",
  studentProfileId text,
  firstNameEn text NOT NULL,
  firstNameFr text,
  lastNameEn text NOT NULL,
  lastNameFr text,
  email text NOT NULL,
  phone text,
  dateOfBirth date,
  specialtyId text NOT NULL,
  levelId text NOT NULL,
  academicYearId text NOT NULL,
  subSystem USER-DEFINED,
  branch USER-DEFINED,
  preferredLocale text NOT NULL DEFAULT 'en'::text,
  documentStorageKeys ARRAY DEFAULT ARRAY[]::text[],
  rejectionReason text,
  reviewedAt timestamp without time zone,
  reviewedByUserId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT EnrollmentApplication_pkey PRIMARY KEY (id),
  CONSTRAINT EnrollmentApplication_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT EnrollmentApplication_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(id),
  CONSTRAINT EnrollmentApplication_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(id),
  CONSTRAINT EnrollmentApplication_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT EnrollmentApplication_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT EnrollmentApplication_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(id),
  CONSTRAINT EnrollmentApplication_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(id),
  CONSTRAINT EnrollmentApplication_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT EnrollmentApplication_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT EnrollmentApplication_levelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(id),
  CONSTRAINT EnrollmentApplication_levelId_tenantId_fkey FOREIGN KEY (levelId) REFERENCES public.Level(id),
  CONSTRAINT EnrollmentApplication_levelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(tenantId),
  CONSTRAINT EnrollmentApplication_levelId_tenantId_fkey FOREIGN KEY (levelId) REFERENCES public.Level(tenantId),
  CONSTRAINT EnrollmentApplication_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(id),
  CONSTRAINT EnrollmentApplication_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT EnrollmentApplication_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT EnrollmentApplication_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT EnrollmentApplication_reviewedByUserId_fkey FOREIGN KEY (reviewedByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.ExamSession (
  id text NOT NULL,
  tenantId text NOT NULL,
  academicYearId text NOT NULL,
  courseId text NOT NULL,
  termId text NOT NULL,
  sequenceId text,
  type USER-DEFINED NOT NULL DEFAULT 'NORMAL'::"ExamSessionType",
  startsOn date NOT NULL,
  endsOn date NOT NULL,
  finalizedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT ExamSession_pkey PRIMARY KEY (id),
  CONSTRAINT ExamSession_termId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Term(id),
  CONSTRAINT ExamSession_termId_tenantId_fkey FOREIGN KEY (termId) REFERENCES public.Term(id),
  CONSTRAINT ExamSession_termId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Term(tenantId),
  CONSTRAINT ExamSession_termId_tenantId_fkey FOREIGN KEY (termId) REFERENCES public.Term(tenantId),
  CONSTRAINT ExamSession_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT ExamSession_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(id),
  CONSTRAINT ExamSession_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT ExamSession_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT ExamSession_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT ExamSession_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(id),
  CONSTRAINT ExamSession_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(id),
  CONSTRAINT ExamSession_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(tenantId),
  CONSTRAINT ExamSession_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(tenantId),
  CONSTRAINT ExamSession_sequenceId_fkey FOREIGN KEY (sequenceId) REFERENCES public.AcademicSequence(id)
);
CREATE TABLE public.GuardianStudentLink (
  id text NOT NULL,
  tenantId text NOT NULL,
  studentProfileId text NOT NULL,
  guardianUserId text NOT NULL,
  relationshipLabel text,
  consentGrantedAt timestamp without time zone,
  consentRevokedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT GuardianStudentLink_pkey PRIMARY KEY (id),
  CONSTRAINT GuardianStudentLink_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT GuardianStudentLink_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(id),
  CONSTRAINT GuardianStudentLink_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(id),
  CONSTRAINT GuardianStudentLink_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT GuardianStudentLink_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT GuardianStudentLink_guardianUserId_fkey FOREIGN KEY (guardianUserId) REFERENCES public.User(id)
);
CREATE TABLE public.Level (
  id text NOT NULL,
  tenantId text NOT NULL,
  specialtyId text NOT NULL,
  number integer NOT NULL CHECK (number >= 1 AND number <= 10),
  labelEn text,
  labelFr text,
  sortOrder integer,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT Level_pkey PRIMARY KEY (id),
  CONSTRAINT Level_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT Level_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(id),
  CONSTRAINT Level_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(id),
  CONSTRAINT Level_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT Level_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(tenantId)
);
CREATE TABLE public.Message (
  id text NOT NULL,
  tenantId text NOT NULL,
  threadId text NOT NULL,
  senderUserId text NOT NULL,
  body text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT Message_pkey PRIMARY KEY (id),
  CONSTRAINT Message_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT Message_threadId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.MessageThread(id),
  CONSTRAINT Message_threadId_tenantId_fkey FOREIGN KEY (threadId) REFERENCES public.MessageThread(id),
  CONSTRAINT Message_threadId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.MessageThread(tenantId),
  CONSTRAINT Message_threadId_tenantId_fkey FOREIGN KEY (threadId) REFERENCES public.MessageThread(tenantId),
  CONSTRAINT Message_senderUserId_fkey FOREIGN KEY (senderUserId) REFERENCES public.User(id)
);
CREATE TABLE public.MessageThread (
  id text NOT NULL,
  tenantId text NOT NULL,
  kind USER-DEFINED NOT NULL,
  subjectEn text,
  subjectFr text,
  groupScope USER-DEFINED,
  groupScopeId text,
  createdByUserId text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT MessageThread_pkey PRIMARY KEY (id),
  CONSTRAINT MessageThread_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT MessageThread_createdByUserId_fkey FOREIGN KEY (createdByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.MessageThreadMember (
  id text NOT NULL,
  tenantId text NOT NULL,
  threadId text NOT NULL,
  userId text NOT NULL,
  joinedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastReadAt timestamp without time zone,
  CONSTRAINT MessageThreadMember_pkey PRIMARY KEY (id),
  CONSTRAINT MessageThreadMember_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT MessageThreadMember_threadId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.MessageThread(id),
  CONSTRAINT MessageThreadMember_threadId_tenantId_fkey FOREIGN KEY (threadId) REFERENCES public.MessageThread(id),
  CONSTRAINT MessageThreadMember_threadId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.MessageThread(tenantId),
  CONSTRAINT MessageThreadMember_threadId_tenantId_fkey FOREIGN KEY (threadId) REFERENCES public.MessageThread(tenantId),
  CONSTRAINT MessageThreadMember_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.Notification (
  id text NOT NULL,
  tenantId text NOT NULL,
  userId text NOT NULL,
  event text NOT NULL,
  titleEn text NOT NULL,
  titleFr text NOT NULL,
  bodyEn text,
  bodyFr text,
  data jsonb,
  readAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT Notification_pkey PRIMARY KEY (id),
  CONSTRAINT Notification_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT Notification_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.NotificationPreference (
  id text NOT NULL,
  tenantId text NOT NULL,
  userId text NOT NULL,
  event text NOT NULL,
  inApp boolean NOT NULL DEFAULT true,
  email boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT NotificationPreference_pkey PRIMARY KEY (id),
  CONSTRAINT NotificationPreference_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT NotificationPreference_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.Room (
  id text NOT NULL,
  tenantId text NOT NULL,
  code text NOT NULL,
  nameEn text NOT NULL,
  nameFr text NOT NULL,
  capacity integer,
  building text,
  isActive boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Room_pkey PRIMARY KEY (id),
  CONSTRAINT Room_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id)
);
CREATE TABLE public.ScholarshipType (
  id text NOT NULL,
  tenantId text NOT NULL,
  nameEn text NOT NULL,
  nameFr text NOT NULL,
  discountKind USER-DEFINED NOT NULL,
  percentBps integer,
  fixedAmountMinor bigint,
  isActive boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT ScholarshipType_pkey PRIMARY KEY (id),
  CONSTRAINT ScholarshipType_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id)
);
CREATE TABLE public.Term (
  id text NOT NULL,
  tenantId text NOT NULL,
  academicYearId text NOT NULL,
  levelId text,
  number integer NOT NULL CHECK (number = ANY (ARRAY[1, 2, 3])),
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT Term_pkey PRIMARY KEY (id),
  CONSTRAINT Term_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT Term_academicYearId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT Term_tenantId_academicYearId_number_key UNIQUE (tenantId, academicYearId, number),
  CONSTRAINT Term_levelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(id),
  CONSTRAINT Term_levelId_tenantId_fkey FOREIGN KEY (levelId) REFERENCES public.Level(id),
  CONSTRAINT Term_levelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(tenantId),
  CONSTRAINT Term_levelId_tenantId_fkey FOREIGN KEY (levelId) REFERENCES public.Level(tenantId)
);
CREATE TABLE public.AcademicSequence (
  id text NOT NULL,
  tenantId text NOT NULL,
  academicYearId text NOT NULL,
  termId text NOT NULL,
  number integer NOT NULL CHECK (number >= 1 AND number <= 6),
  numberInTerm integer NOT NULL CHECK (numberInTerm = ANY (ARRAY[1, 2])),
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT AcademicSequence_pkey PRIMARY KEY (id),
  CONSTRAINT AcademicSequence_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT AcademicSequence_academicYearId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT AcademicSequence_termId_fkey FOREIGN KEY (termId) REFERENCES public.Term(id),
  CONSTRAINT AcademicSequence_tenantId_academicYearId_number_key UNIQUE (tenantId, academicYearId, number)
);
CREATE TABLE public.Session (
  id text NOT NULL,
  sessionToken text NOT NULL,
  userId text NOT NULL,
  expires timestamp without time zone NOT NULL,
  CONSTRAINT Session_pkey PRIMARY KEY (id),
  CONSTRAINT Session_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.Specialty (
  id text NOT NULL,
  tenantId text NOT NULL,
  departmentId text NOT NULL,
  code text NOT NULL CHECK (length(btrim(code)) > 0),
  nameEn text NOT NULL CHECK (length(btrim("nameEn")) > 0),
  nameFr text NOT NULL CHECK (length(btrim("nameFr")) > 0),
  subSystem USER-DEFINED NOT NULL DEFAULT 'ENGLISH'::"AcademicSubSystem",
  branch USER-DEFINED NOT NULL DEFAULT 'GRAMMAR'::"AcademicBranch",
  durationYears integer NOT NULL CHECK ("durationYears" >= 1 AND "durationYears" <= 10),
  gradingSystem USER-DEFINED NOT NULL,
  gradingLockedAt timestamp without time zone,
  feeAmountMinor bigint NOT NULL DEFAULT 0 CHECK ("feeAmountMinor" >= 0),
  feeCurrency text NOT NULL DEFAULT 'XAF'::text CHECK ("feeCurrency" ~ '^[A-Z]{3}$'::text),
  isPublished boolean NOT NULL DEFAULT false,
  publishedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  customGradingBands jsonb,
  minimumCreditsToGraduate integer,
  CONSTRAINT Specialty_pkey PRIMARY KEY (id),
  CONSTRAINT Specialty_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT Specialty_departmentId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Department(id),
  CONSTRAINT Specialty_departmentId_tenantId_fkey FOREIGN KEY (departmentId) REFERENCES public.Department(id),
  CONSTRAINT Specialty_departmentId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Department(tenantId),
  CONSTRAINT Specialty_departmentId_tenantId_fkey FOREIGN KEY (departmentId) REFERENCES public.Department(tenantId)
);
CREATE TABLE public.SpecialtyFeePlan (
  id text NOT NULL,
  tenantId text NOT NULL,
  specialtyId text NOT NULL,
  installments jsonb NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT SpecialtyFeePlan_pkey PRIMARY KEY (id),
  CONSTRAINT SpecialtyFeePlan_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT SpecialtyFeePlan_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(id),
  CONSTRAINT SpecialtyFeePlan_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(id),
  CONSTRAINT SpecialtyFeePlan_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT SpecialtyFeePlan_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(tenantId)
);
CREATE TABLE public.StaffProfile (
  id text NOT NULL,
  tenantId text NOT NULL,
  userId text NOT NULL,
  staffCode text CHECK ("staffCode" IS NULL OR length(btrim("staffCode")) > 0),
  departmentId text,
  employmentType USER-DEFINED NOT NULL DEFAULT 'FULL_TIME'::"StaffEmploymentType",
  title text CHECK (title IS NULL OR length(btrim(title)) > 0),
  hireDate date,
  officeRoom text CHECK ("officeRoom" IS NULL OR length(btrim("officeRoom")) > 0),
  officePhone text CHECK ("officePhone" IS NULL OR length(btrim("officePhone")) > 0),
  bio text CHECK (bio IS NULL OR length(btrim(bio)) > 0),
  isActive boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT StaffProfile_pkey PRIMARY KEY (id),
  CONSTRAINT StaffProfile_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT StaffProfile_userId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.User(id),
  CONSTRAINT StaffProfile_userId_tenantId_fkey FOREIGN KEY (userId) REFERENCES public.User(id),
  CONSTRAINT StaffProfile_userId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.User(tenantId),
  CONSTRAINT StaffProfile_userId_tenantId_fkey FOREIGN KEY (userId) REFERENCES public.User(tenantId),
  CONSTRAINT StaffProfile_departmentId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Department(id),
  CONSTRAINT StaffProfile_departmentId_tenantId_fkey FOREIGN KEY (departmentId) REFERENCES public.Department(id),
  CONSTRAINT StaffProfile_departmentId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Department(tenantId),
  CONSTRAINT StaffProfile_departmentId_tenantId_fkey FOREIGN KEY (departmentId) REFERENCES public.Department(tenantId)
);
CREATE TABLE public.StudentEnrollment (
  id text NOT NULL,
  tenantId text NOT NULL,
  studentProfileId text NOT NULL,
  academicYearId text NOT NULL,
  specialtyId text NOT NULL,
  levelId text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'ENROLLED'::"StudentEnrollmentStatus",
  applicationId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT StudentEnrollment_pkey PRIMARY KEY (id),
  CONSTRAINT StudentEnrollment_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT StudentEnrollment_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(id),
  CONSTRAINT StudentEnrollment_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(id),
  CONSTRAINT StudentEnrollment_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT StudentEnrollment_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT StudentEnrollment_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(id),
  CONSTRAINT StudentEnrollment_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT StudentEnrollment_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT StudentEnrollment_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT StudentEnrollment_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(id),
  CONSTRAINT StudentEnrollment_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(id),
  CONSTRAINT StudentEnrollment_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT StudentEnrollment_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT StudentEnrollment_levelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(id),
  CONSTRAINT StudentEnrollment_levelId_tenantId_fkey FOREIGN KEY (levelId) REFERENCES public.Level(id),
  CONSTRAINT StudentEnrollment_levelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(tenantId),
  CONSTRAINT StudentEnrollment_levelId_tenantId_fkey FOREIGN KEY (levelId) REFERENCES public.Level(tenantId),
  CONSTRAINT StudentEnrollment_applicationId_fkey FOREIGN KEY (applicationId) REFERENCES public.EnrollmentApplication(id)
);
CREATE TABLE public.StudentFeeAccount (
  id text NOT NULL,
  tenantId text NOT NULL,
  studentProfileId text NOT NULL,
  academicYearId text NOT NULL,
  specialtyId text NOT NULL,
  studentEnrollmentId text,
  totalAmountMinor bigint NOT NULL,
  feeCurrency text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT StudentFeeAccount_pkey PRIMARY KEY (id),
  CONSTRAINT StudentFeeAccount_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT StudentFeeAccount_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(id),
  CONSTRAINT StudentFeeAccount_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(id),
  CONSTRAINT StudentFeeAccount_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT StudentFeeAccount_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT StudentFeeAccount_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(id),
  CONSTRAINT StudentFeeAccount_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT StudentFeeAccount_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT StudentFeeAccount_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT StudentFeeAccount_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(id),
  CONSTRAINT StudentFeeAccount_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(id),
  CONSTRAINT StudentFeeAccount_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT StudentFeeAccount_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT StudentFeeAccount_studentEnrollmentId_fkey FOREIGN KEY (studentEnrollmentId) REFERENCES public.StudentEnrollment(id)
);
CREATE TABLE public.StudentFeeInstallment (
  id text NOT NULL,
  tenantId text NOT NULL,
  studentFeeAccountId text NOT NULL,
  installmentNumber integer NOT NULL,
  labelEn text NOT NULL,
  labelFr text NOT NULL,
  amountMinor bigint NOT NULL,
  dueOn date NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"FeeInstallmentStatus",
  paidAmountMinor bigint,
  paidAt timestamp without time zone,
  notes text,
  updatedByUserId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT StudentFeeInstallment_pkey PRIMARY KEY (id),
  CONSTRAINT StudentFeeInstallment_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT StudentFeeInstallment_studentFeeAccountId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentFeeAccount(id),
  CONSTRAINT StudentFeeInstallment_studentFeeAccountId_tenantId_fkey FOREIGN KEY (studentFeeAccountId) REFERENCES public.StudentFeeAccount(id),
  CONSTRAINT StudentFeeInstallment_studentFeeAccountId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentFeeAccount(tenantId),
  CONSTRAINT StudentFeeInstallment_studentFeeAccountId_tenantId_fkey FOREIGN KEY (studentFeeAccountId) REFERENCES public.StudentFeeAccount(tenantId),
  CONSTRAINT StudentFeeInstallment_updatedByUserId_fkey FOREIGN KEY (updatedByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.StudentProfile (
  id text NOT NULL,
  tenantId text NOT NULL,
  userId text NOT NULL,
  registrationNumber text NOT NULL,
  specialtyId text NOT NULL,
  currentLevelId text NOT NULL,
  isActive boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  alumniSince timestamp without time zone,
  alumniDirectoryOptIn boolean NOT NULL DEFAULT false,
  CONSTRAINT StudentProfile_pkey PRIMARY KEY (id),
  CONSTRAINT StudentProfile_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT StudentProfile_userId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.User(id),
  CONSTRAINT StudentProfile_userId_tenantId_fkey FOREIGN KEY (userId) REFERENCES public.User(id),
  CONSTRAINT StudentProfile_userId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.User(tenantId),
  CONSTRAINT StudentProfile_userId_tenantId_fkey FOREIGN KEY (userId) REFERENCES public.User(tenantId),
  CONSTRAINT StudentProfile_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(id),
  CONSTRAINT StudentProfile_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(id),
  CONSTRAINT StudentProfile_specialtyId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT StudentProfile_specialtyId_tenantId_fkey FOREIGN KEY (specialtyId) REFERENCES public.Specialty(tenantId),
  CONSTRAINT StudentProfile_currentLevelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(id),
  CONSTRAINT StudentProfile_currentLevelId_tenantId_fkey FOREIGN KEY (currentLevelId) REFERENCES public.Level(id),
  CONSTRAINT StudentProfile_currentLevelId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Level(tenantId),
  CONSTRAINT StudentProfile_currentLevelId_tenantId_fkey FOREIGN KEY (currentLevelId) REFERENCES public.Level(tenantId)
);
CREATE TABLE public.StudentScholarship (
  id text NOT NULL,
  tenantId text NOT NULL,
  studentFeeAccountId text NOT NULL,
  scholarshipTypeId text NOT NULL,
  discountMinor bigint NOT NULL,
  grantedByUserId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT StudentScholarship_pkey PRIMARY KEY (id),
  CONSTRAINT StudentScholarship_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT StudentScholarship_studentFeeAccountId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentFeeAccount(id),
  CONSTRAINT StudentScholarship_studentFeeAccountId_tenantId_fkey FOREIGN KEY (studentFeeAccountId) REFERENCES public.StudentFeeAccount(id),
  CONSTRAINT StudentScholarship_studentFeeAccountId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentFeeAccount(tenantId),
  CONSTRAINT StudentScholarship_studentFeeAccountId_tenantId_fkey FOREIGN KEY (studentFeeAccountId) REFERENCES public.StudentFeeAccount(tenantId),
  CONSTRAINT StudentScholarship_scholarshipTypeId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.ScholarshipType(id),
  CONSTRAINT StudentScholarship_scholarshipTypeId_tenantId_fkey FOREIGN KEY (scholarshipTypeId) REFERENCES public.ScholarshipType(id),
  CONSTRAINT StudentScholarship_scholarshipTypeId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.ScholarshipType(tenantId),
  CONSTRAINT StudentScholarship_scholarshipTypeId_tenantId_fkey FOREIGN KEY (scholarshipTypeId) REFERENCES public.ScholarshipType(tenantId),
  CONSTRAINT StudentScholarship_grantedByUserId_fkey FOREIGN KEY (grantedByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.SystemLog (
  id text NOT NULL,
  userId text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  entityId text,
  entityType text,
  event text,
  description text,
  ipAddress text,
  meta text,
  CONSTRAINT SystemLog_pkey PRIMARY KEY (id),
  CONSTRAINT SystemLog_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.SystemSetting (
  id text NOT NULL,
  name text NOT NULL DEFAULT 'My Company'::text,
  logo text,
  active boolean NOT NULL DEFAULT true,
  address text,
  websiteURL text,
  supportEmail text,
  supportPhone text,
  language text NOT NULL DEFAULT 'en'::text,
  timezone text NOT NULL DEFAULT 'UTC'::text,
  currency text NOT NULL DEFAULT 'USD'::text,
  currencyFormat text NOT NULL DEFAULT '$ {value}'::text,
  socialFacebook text,
  socialTwitter text,
  socialInstagram text,
  socialLinkedIn text,
  socialPinterest text,
  socialYoutube text,
  notifyStockEmail boolean NOT NULL DEFAULT true,
  notifyStockWeb boolean NOT NULL DEFAULT true,
  notifyStockThreshold integer NOT NULL DEFAULT 10,
  notifyStockRoleIds ARRAY,
  notifyNewOrderEmail boolean NOT NULL DEFAULT true,
  notifyNewOrderWeb boolean NOT NULL DEFAULT true,
  notifyNewOrderRoleIds ARRAY,
  notifyOrderStatusUpdateEmail boolean NOT NULL DEFAULT true,
  notifyOrderStatusUpdateWeb boolean NOT NULL DEFAULT true,
  notifyOrderStatusUpdateRoleIds ARRAY,
  notifyPaymentFailureEmail boolean NOT NULL DEFAULT true,
  notifyPaymentFailureWeb boolean NOT NULL DEFAULT true,
  notifyPaymentFailureRoleIds ARRAY,
  notifySystemErrorFailureEmail boolean NOT NULL DEFAULT true,
  notifySystemErrorWeb boolean NOT NULL DEFAULT true,
  notifySystemErrorRoleIds ARRAY,
  CONSTRAINT SystemSetting_pkey PRIMARY KEY (id)
);
CREATE TABLE public.Tenant (
  id text NOT NULL,
  slug text NOT NULL,
  displayNameEn text NOT NULL,
  displayNameFr text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'ONBOARDING'::"TenantStatus",
  deploymentMode USER-DEFINED NOT NULL DEFAULT 'CLOUD'::"DeploymentMode",
  planSlug text,
  locale text NOT NULL DEFAULT 'en'::text,
  timezone text NOT NULL DEFAULT 'UTC'::text,
  country text,
  logoStorageKey text,
  primaryColor text,
  accentColor text,
  onboardingCompletedAt timestamp without time zone,
  suspendedAt timestamp without time zone,
  archivedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  sessionTimeoutMinutes integer NOT NULL DEFAULT 480,
  sessionWarningMinutes integer NOT NULL DEFAULT 5,
  institutionEmail text,
  institutionPhone text,
  addressLine1 text,
  addressLine2 text,
  city text,
  region text,
  websiteUrl text,
  secondaryContactName text,
  secondaryContactEmail text,
  academicYearStartMonth integer CHECK ("academicYearStartMonth" IS NULL OR "academicYearStartMonth" >= 1 AND "academicYearStartMonth" <= 12),
  defaultGradingMode USER-DEFINED,
  enabledModules ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  smtpHost text,
  smtpPort integer,
  smtpUser text,
  smtpPassEncrypted text,
  smtpFromEmail text,
  usePlatformEmailRelay boolean NOT NULL DEFAULT true,
  markEntryCalendarPolicy USER-DEFINED NOT NULL DEFAULT 'SESSION_DATES_ONLY'::"MarkEntryCalendarPolicy",
  minimumAttendancePercent integer NOT NULL DEFAULT 75,
  showAttendanceOnTranscript boolean NOT NULL DEFAULT false,
  customDomain character varying,
  customDomainVerificationToken text,
  customDomainVerifiedAt timestamp without time zone,
  pdfIssuerDisplayNameEn text,
  pdfIssuerDisplayNameFr text,
  CONSTRAINT Tenant_pkey PRIMARY KEY (id)
);
CREATE TABLE public.TenantApiKey (
  id text NOT NULL,
  tenantId text NOT NULL,
  name text NOT NULL,
  keyPrefix text NOT NULL,
  keyHash text NOT NULL,
  scopes ARRAY NOT NULL,
  createdByUserId text NOT NULL,
  lastUsedAt timestamp without time zone,
  revokedAt timestamp without time zone,
  expiresAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT TenantApiKey_pkey PRIMARY KEY (id),
  CONSTRAINT TenantApiKey_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT TenantApiKey_createdByUserId_fkey FOREIGN KEY (createdByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.TimetableSlot (
  id text NOT NULL,
  tenantId text NOT NULL,
  academicYearId text NOT NULL,
  courseId text NOT NULL,
  staffProfileId text NOT NULL,
  roomId text NOT NULL,
  dayOfWeek integer NOT NULL CHECK ("dayOfWeek" >= 1 AND "dayOfWeek" <= 7),
  startMinutes integer NOT NULL,
  endMinutes integer NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT TimetableSlot_pkey PRIMARY KEY (id),
  CONSTRAINT TimetableSlot_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT TimetableSlot_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(id),
  CONSTRAINT TimetableSlot_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT TimetableSlot_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT TimetableSlot_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT TimetableSlot_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(id),
  CONSTRAINT TimetableSlot_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(id),
  CONSTRAINT TimetableSlot_courseId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Course(tenantId),
  CONSTRAINT TimetableSlot_courseId_tenantId_fkey FOREIGN KEY (courseId) REFERENCES public.Course(tenantId),
  CONSTRAINT TimetableSlot_staffProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StaffProfile(id),
  CONSTRAINT TimetableSlot_staffProfileId_tenantId_fkey FOREIGN KEY (staffProfileId) REFERENCES public.StaffProfile(id),
  CONSTRAINT TimetableSlot_staffProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StaffProfile(tenantId),
  CONSTRAINT TimetableSlot_staffProfileId_tenantId_fkey FOREIGN KEY (staffProfileId) REFERENCES public.StaffProfile(tenantId),
  CONSTRAINT TimetableSlot_roomId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Room(id),
  CONSTRAINT TimetableSlot_roomId_tenantId_fkey FOREIGN KEY (roomId) REFERENCES public.Room(id),
  CONSTRAINT TimetableSlot_roomId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Room(tenantId),
  CONSTRAINT TimetableSlot_roomId_tenantId_fkey FOREIGN KEY (roomId) REFERENCES public.Room(tenantId)
);
CREATE TABLE public.Transcript (
  id text NOT NULL,
  tenantId text NOT NULL,
  studentProfileId text NOT NULL,
  termId text NOT NULL,
  academicYearId text NOT NULL,
  currentVersionId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Transcript_pkey PRIMARY KEY (id),
  CONSTRAINT Transcript_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT Transcript_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(id),
  CONSTRAINT Transcript_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(id),
  CONSTRAINT Transcript_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT Transcript_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT Transcript_termId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Term(id),
  CONSTRAINT Transcript_termId_tenantId_fkey FOREIGN KEY (termId) REFERENCES public.Term(id),
  CONSTRAINT Transcript_termId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Term(tenantId),
  CONSTRAINT Transcript_termId_tenantId_fkey FOREIGN KEY (termId) REFERENCES public.Term(tenantId),
  CONSTRAINT Transcript_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(id),
  CONSTRAINT Transcript_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(id),
  CONSTRAINT Transcript_academicYearId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT Transcript_academicYearId_tenantId_fkey FOREIGN KEY (academicYearId) REFERENCES public.AcademicYear(tenantId),
  CONSTRAINT Transcript_currentVersionId_fkey FOREIGN KEY (currentVersionId) REFERENCES public.TranscriptVersion(id)
);
CREATE TABLE public.TranscriptCopyRequest (
  id text NOT NULL,
  tenantId text NOT NULL,
  studentProfileId text NOT NULL,
  requestedByUserId text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"TranscriptCopyRequestStatus",
  note text,
  resolvedAt timestamp without time zone,
  resolvedByUserId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT TranscriptCopyRequest_pkey PRIMARY KEY (id),
  CONSTRAINT TranscriptCopyRequest_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT TranscriptCopyRequest_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(id),
  CONSTRAINT TranscriptCopyRequest_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(id),
  CONSTRAINT TranscriptCopyRequest_studentProfileId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT TranscriptCopyRequest_studentProfileId_tenantId_fkey FOREIGN KEY (studentProfileId) REFERENCES public.StudentProfile(tenantId),
  CONSTRAINT TranscriptCopyRequest_requestedByUserId_fkey FOREIGN KEY (requestedByUserId) REFERENCES public.User(id),
  CONSTRAINT TranscriptCopyRequest_resolvedByUserId_fkey FOREIGN KEY (resolvedByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.TranscriptVersion (
  id text NOT NULL,
  tenantId text NOT NULL,
  transcriptId text NOT NULL,
  versionNumber integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"TranscriptVersionStatus",
  pdfStorageKey text,
  qrToken text NOT NULL,
  issuedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  issuedByUserId text,
  reissueReason text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT TranscriptVersion_pkey PRIMARY KEY (id),
  CONSTRAINT TranscriptVersion_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id),
  CONSTRAINT TranscriptVersion_transcriptId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Transcript(id),
  CONSTRAINT TranscriptVersion_transcriptId_tenantId_fkey FOREIGN KEY (transcriptId) REFERENCES public.Transcript(id),
  CONSTRAINT TranscriptVersion_transcriptId_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Transcript(tenantId),
  CONSTRAINT TranscriptVersion_transcriptId_tenantId_fkey FOREIGN KEY (transcriptId) REFERENCES public.Transcript(tenantId),
  CONSTRAINT TranscriptVersion_issuedByUserId_fkey FOREIGN KEY (issuedByUserId) REFERENCES public.User(id)
);
CREATE TABLE public.User (
  id text NOT NULL,
  email text NOT NULL,
  password text,
  country text,
  timezone text,
  name text,
  roleId text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'INACTIVE'::"UserStatus",
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  lastSignInAt timestamp without time zone,
  emailVerifiedAt timestamp without time zone,
  isTrashed boolean NOT NULL DEFAULT false,
  avatar text,
  invitedByUserId text,
  isProtected boolean NOT NULL DEFAULT false,
  tenantId text,
  totpSecretEncrypted text,
  totpEnabledAt timestamp without time zone,
  totpLastVerifiedAt timestamp without time zone,
  CONSTRAINT User_pkey PRIMARY KEY (id),
  CONSTRAINT User_roleId_fkey FOREIGN KEY (roleId) REFERENCES public.UserRole(id),
  CONSTRAINT User_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.Tenant(id)
);
CREATE TABLE public.UserPermission (
  id text NOT NULL,
  slug text NOT NULL,
  name text NOT NULL,
  description text,
  createdByUserId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UserPermission_pkey PRIMARY KEY (id)
);
CREATE TABLE public.UserRole (
  id text NOT NULL,
  slug text NOT NULL,
  name text NOT NULL,
  description text,
  isTrashed boolean NOT NULL DEFAULT false,
  createdByUserId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  isProtected boolean NOT NULL DEFAULT false,
  isDefault boolean NOT NULL DEFAULT false,
  CONSTRAINT UserRole_pkey PRIMARY KEY (id)
);
CREATE TABLE public.UserRolePermission (
  id text NOT NULL,
  roleId text NOT NULL,
  permissionId text NOT NULL,
  assignedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UserRolePermission_pkey PRIMARY KEY (id),
  CONSTRAINT UserRolePermission_roleId_fkey FOREIGN KEY (roleId) REFERENCES public.UserRole(id),
  CONSTRAINT UserRolePermission_permissionId_fkey FOREIGN KEY (permissionId) REFERENCES public.UserPermission(id)
);
CREATE TABLE public.VerificationToken (
  identifier text NOT NULL,
  token text NOT NULL,
  expires timestamp without time zone NOT NULL
);
CREATE TABLE public._prisma_migrations (
  id character varying NOT NULL,
  checksum character varying NOT NULL,
  finished_at timestamp with time zone,
  migration_name character varying NOT NULL,
  logs text,
  rolled_back_at timestamp with time zone,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  applied_steps_count integer NOT NULL DEFAULT 0,
  CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
);