import type { KeenIconName } from './keen-icon-names';

/** Maps Lucide React export names to Keenicons duotone glyph names. */
export const LUCIDE_TO_KEEN = {
  AlertCircle: 'information',
  AlertTriangle: 'information-2',
  ArrowLeft: 'arrow-left',
  ArrowRightLeft: 'arrow-right-left',
  ChevronRight: 'arrow-right',
  MoveLeft: 'arrow-left',
  UserPen: 'pencil',
  Activity: 'chart',
  BarChart3: 'chart',
  Bell: 'notification',
  Book: 'book',
  BookOpen: 'book-open',
  Building: 'bank',
  CalendarCheck: 'calendar-tick',
  Check: 'check',
  ClipboardList: 'clipboard',
  DollarSign: 'dollar',
  Download: 'file-down',
  ExternalLink: 'exit-up',
  Eye: 'eye',
  EyeOff: 'eye-slash',
  FileCheck: 'check-squared',
  FileText: 'file-sheet',
  FolderOpen: 'folder',
  GraduationCap: 'teacher',
  KeyRound: 'key',
  LayoutGrid: 'element-11',
  LoaderCircleIcon: 'loading',
  LogIn: 'security-user',
  MessageSquare: 'message-text',
  MoreHorizontal: 'dots-horizontal',
  Ellipsis: 'dots-horizontal',
  ShieldAlert: 'shield-tick',
  UserRound: 'user-tick',
  AppWindowMac: 'element-11',
  MailWarning: 'information-2',
  Pencil: 'pencil',
  Plus: 'plus',
  Printer: 'printer',
  ScrollText: 'document',
  Search: 'magnifier',
  Settings: 'setting-2',
  Shield: 'shield-tick',
  Star: 'star',
  Trash2: 'trash',
  Upload: 'file-up',
  UserPlus: 'user-tick',
  Users: 'users',
  Wallet: 'wallet',
  X: 'cross',
} as const satisfies Record<string, KeenIconName>;

export type LucideExportName = keyof typeof LUCIDE_TO_KEEN;
